- hosts: "{{ env }}"
  become: yes
  tasks: 
    - name: Deploying Application pods...
      shell: | 
         if [ `kubectl get deployment | grep -v NAME | awk '{print $1}' | grep eduproj | wc -l` -gt 0 ]; then  
            echo "deleteing previous application deployment"
            kubectl delete deployment `kubectl get deployment | grep -v NAME | awk '{print $1}' | grep eduproj`
            echo "creating new application deployment"
            kubectl create deployment eduproj --image=irfanhaneefcl/edureka_project2:{{ build }}
         else 
            echo "Deploying eduproj Application"
            kubectl create deployment eduproj --image=irfanhaneefcl/edureka_project2:{{ build }}
         fi
    - name: deploying service
      shell: |
         if [ `kubectl get svc | grep eduproj  | awk '{print $1}' | wc -l` -gt 0 ]; then
            echo "app service found, No actions taken"
            #kubectl delete svc `kubectl get svc | grep eduproj | awk '{print $1}'`
         else
            echo "Creating App Services"
            kubectl expose deployment eduproj --name eduproj --type NodePort --port 80 --target-port 8080
         fi
    - name: increase replicas 
      shell: kubectl scale deploy eduproj --replicas=5
      
    #- name: deploy app
    #  shell: kubectl create deployment eduproj --image=irfanhaneefcl/edureka_project2:{{ build }}
    #- name: deploy service
    #  shell: kubectl expose deployment eduproj --name eduproj --type NodePort --port 80 --target-port 8080
